/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as PortfolioRouteImport } from './routes/portfolio.tsx'
import { Route as LegalRouteImport } from './routes/legal.tsx'
import { Route as ApplyRouteImport } from './routes/apply.tsx'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertySlugRouteImport } from './routes/property.$slug.tsx'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/property/$slug': typeof PropertySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/property/$slug': typeof PropertySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/property/$slug': typeof PropertySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apply' | '/legal' | '/portfolio' | '/property/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apply' | '/legal' | '/portfolio' | '/property/$slug'
  id: '__root__' | '/' | '/apply' | '/legal' | '/portfolio' | '/property/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  LegalRoute: typeof LegalRoute
  PortfolioRoute: typeof PortfolioRoute
  PropertySlugRoute: typeof PropertySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  LegalRoute: LegalRoute,
  PortfolioRoute: PortfolioRoute,
  PropertySlugRoute: PropertySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
